name: Daily Deals Update

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 04:00 UTC every day (06:00 South Africa time)
    - cron: '0 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Need full history to commit & push
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create & activate virtualenv, install deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Takealot scraper
        run: |
          source venv/bin/activate
          python scraper_takealot_sqlite.py

      - name: Run Loot scraper
        run: |
          source venv/bin/activate
          python scraper_loot_dom.py

      - name: Render HTML
        run: |
          source venv/bin/activate
          python render_deals.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Automated daily update: $(date -u +"%Y-%m-%d")" || echo "No changes to commit"
          git push origin main

      - name: Send email alerts
        if: always()
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          source venv/bin/activate
          python email_deals.py
