# .github/workflows/update-deals.yml
name: Daily Deals Update

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 04:00 UTC daily (~06:00 SAST)
    - cron: '0 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2) Install Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3) Install EXACT OS packages (Ubuntu 24.04) that headless Chromium needs
      - name: Install system dependencies for Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 \
            libcups2 libdrm2 libxkbcommon0 libxcomposite1 \
            libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2t64

      # 4) Create venv & install Python packages
      - name: Create venv & install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate

          pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt

          # Let Playwright install its browsers (no install-deps this time)
          playwright install chromium

      # 5) Run Takealot scraper (allow failure to collect debug HTML if zero deals)
      - name: Run Takealot scraper
        run: |
          source venv/bin/activate
          python scraper_takealot_sqlite.py || true
          if [ -f takealot_debug.html ]; then
            echo "→ takealot_debug.html generated for investigation"
          fi

      # 6) Run Loot scraper
      - name: Run Loot scraper
        run: |
          source venv/bin/activate
          python scraper_loot_dom.py

      # 7) Clean out deals older than 30 days
      - name: Clean old deals
        run: |
          source venv/bin/activate
          python cleanup.py

      # 8) Render index.html
      - name: Render HTML
        run: |
          source venv/bin/activate
          python render_deals.py

      # 9) Commit & push index.html if it changed
      - name: Commit & push changes
        run: |
          git reset --hard HEAD
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage only index.html (never deals.db)
          git add index.html

          if git diff --cached --quiet; then
            echo "No changes to index.html → skipping push."
            exit 0
          fi

          git commit -m "Automated daily update: $(date -u +'%Y-%m-%d %H:%M UTC')"
          git pull --rebase origin main
          git push origin main

      # 10) If Takealot found zero deals (i.e. step 5 exited nonzero), upload debug HTML
      - name: Upload takealot_debug.html (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: takealot-debug
          path: takealot_debug.html
