# .github/workflows/update-deals.yml
name: Daily Deals Update

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 04:00 UTC every day (~06:00 SAST)
    - cron: '0 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2) Install Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3) Create venv & install pip packages
      - name: Create venv & install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate

          pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt

          # Let Playwright install whatever Debian/Ubuntu libraries Chromium needs:
          playwright install-deps chromium
          playwright install chromium

      # 4) Run Takealot scraper (allow failure so we still collect debug HTML)
      - name: Run Takealot scraper
        run: |
          source venv/bin/activate
          python scraper_takealot_sqlite.py || true
          if [ -f takealot_debug.html ]; then
            echo "→ takealot_debug.html was generated."
          fi

      # 5) Run Loot scraper
      - name: Run Loot scraper
        run: |
          source venv/bin/activate
          python scraper_loot_dom.py

      # 6) Clean out any deals older than 30 days
      - name: Clean old deals
        run: |
          source venv/bin/activate
          python cleanup.py

      # 7) Render index.html
      - name: Render HTML
        run: |
          source venv/bin/activate
          python render_deals.py

      # 8) Commit & push index.html if it changed
      - name: Commit & push changes
        run: |
          git reset --hard HEAD
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage only index.html (never deals.db)
          git add index.html

          if git diff --cached --quiet; then
            echo "No changes to index.html → skipping push."
            exit 0
          fi

          git commit -m "Automated daily update: $(date -u +'%Y-%m-%d %H:%M UTC')"
          git pull --rebase origin main
          git push origin main

      # 9) If Takealot finds zero deals, upload debug HTML
      - name: Upload takealot_debug.html (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: takealot-debug
          path: takealot_debug.html

