name: Daily Deals Update

on:
  push:
    branches:
      - main
  schedule:
    # Runs at 04:00 UTC every day (06:00 SAST)
    - cron: '0 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository (full history)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Create venv & install dependencies
      - name: Create venv & install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps chromium

      # 4) Run Takealot scraper (with debug HTML upload if no deals)
      - name: Run Takealot scraper
        run: |
          source venv/bin/activate
          python scraper_takealot_sqlite.py || true
          if [ -f takealot_debug.html ]; then
            echo "----- takealot_debug.html exists -----"
            ls -lh takealot_debug.html
          else
            echo "No debug HTML"
          fi

      # 5) Run Loot scraper
      - name: Run Loot scraper
        run: |
          source venv/bin/activate
          python scraper_loot_dom.py

      # 6) (Optional) Clean up old deals from the DB
      - name: Clean old deals
        run: |
          source venv/bin/activate
          python cleanup.py

      # 7) Render index.html from DB
      - name: Render HTML
        run: |
          source venv/bin/activate
          python render_deals.py

      # 8) Commit & push only if index.html changed
      - name: Commit & push changes
        run: |
          # Discard any unintended modifications
          git reset --hard HEAD

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage only index.html
          git add index.html

          # If there are no changes, skip push
          if git diff --cached --quiet; then
            echo "No changes to commit → skipping push."
            exit 0
          fi

          # Otherwise commit & rebase on main then push
          git commit -m "Automated daily update: $(date -u +'%Y-%m-%d %H:%M UTC')"
          git pull --rebase origin main
          git push origin main

      # 9) Always upload debug HTML if it exists
      - name: Upload debug HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: takealot-debug
          path: takealot_debug.html

