# File: .github/workflows/update-deals.yml
name: Daily Deals Update

on:
  push:
    branches:
      - main
  schedule:
    # Every day at 04:00 UTC (≈ 06:00 SAST)
    - cron: '0 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2) Use Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3) Install just the packages needed to build lxml
      - name: Install system dependencies for lxml
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxml2-dev libxslt-dev python3-dev

      # 4) Create a venv & install your pip requirements + Playwright
      - name: Create venv & install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate

          pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt

          # Let Playwright pull in any remaining Chromium dependencies:
          playwright install chromium
          playwright install-deps chromium

      # 5) Run Takealot scraper
      - name: Run Takealot scraper
        run: |
          source venv/bin/activate
          python scraper_takealot_sqlite.py || true

          # If the scraper saw no deals, it will drop takealot_debug.html in workspace:
          if [ -f takealot_debug.html ]; then
            echo "⚠️  takealot_debug.html is present → download via artifact."
          fi

      # 6) Run Loot scraper
      - name: Run Loot scraper
        run: |
          source venv/bin/activate
          python scraper_loot_dom.py

      # 7) Cleanup old deals (>30 days)
      - name: Clean old deals
        run: |
          source venv/bin/activate
          python cleanup.py

      # 8) Render index.html
      - name: Render HTML
        run: |
          source venv/bin/activate
          python render_deals.py

      # 9) Commit & push only if index.html changed
      - name: Commit & push changes
        run: |
          git reset --hard HEAD

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage index.html (never deals.db)
          git add index.html

          if git diff --cached --quiet; then
            echo "No changes to index.html → skipping push."
            exit 0
          fi

          git commit -m "Automated daily update: $(date -u +'%Y-%m-%d %H:%M UTC')"
          git pull --rebase origin main
          git push origin main

      # 10) If Takealot produced a debug file, upload it
      - name: Upload takealot_debug.html (if present)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: takealot-debug
          path: takealot_debug.html
