name: Update Deals Site

on:
  schedule:
    # Runs at 06:00 and 18:00 UTC (08:00 & 20:00 SAST)
    - cron: '0 6,18 * * *'
  workflow_dispatch:   # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true    # allows pushes with GITHUB_TOKEN
          fetch-depth: 0              # fetch all history for proper commits

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run scraper → update SQLite
        run: python scraper_takealot_sqlite.py

      - name: Render today's HTML
        run: python render_deals.py

      - name: Send email alerts
        if: always()
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: python email_deals.py

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add deals.db index.html
          # Commit only when there are changes
          git diff --quiet && echo "No changes to commit" || git commit -m "Automated update: $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push origin main

